name = "BakerStreet"
uuid = "79c3fcf7-ab10-4df2-b330-e2e1bedd9b25"
authors = ["Kristof Cools <krcools@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
DataFrames = "1.7.0"
DrWatson = "2.14"
MacroTools = "0.5.13"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
